
name: CI

on: [push]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: echo a string
        run: echo "hello world"
      - name: pwd
        run: pwd 
      - name: cd
        run: cd /home/runner/work/Javier6-11-
      - name: ls
        run: ls /home/runner/work/Javier6-11-
      - name: cat
        run: cat > ComandosLinux.txt
        
        
      - name: cp
        run: cp ComandosLinux.txt /home/runner/work/Javier6-11-/Comandos/etc
