
name: CI

on: [push]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: echo a string
        run: echo "hello world"
      - name: cd
        run: cd Javier6-11-
      - name: cp
        run: cp ComandosLinux.txt Comandos/etc
